apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: blog-api-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: blog-api
  type: LoadBalancer
status:
  loadBalancer: {}
